[build]
  base = "frontend"
  command = "npm run build:prod"
  # Relative to base (frontend/)
  publish = "dist/frontend/browser"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
